server {
  listen 80;
  server_name 127.0.0.1;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ {
    proxy_pass http://api:8765;
    proxy_set_header Host $host;
  }
  location /openapi.json {
    proxy_pass http://api:8765;
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
}
