"""Technology-neutral persistence contract used by V1 services."""

from __future__ import annotations

from typing import Any, Protocol


class RepositoryPort(Protocol):
    """Logical repository operations shared by SQLite and PostgreSQL adapters."""

    backend: str

    def initialize(self) -> None: ...
    def get_settings(self) -> dict[str, str]: ...
    def update_settings(self, values: dict[str, int]) -> dict[str, str]: ...
    def audit(self, event_type: str, entity_id: str | None, result: str) -> None: ...
    def create_ingest(self, **values: Any) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]: ...
    def list_sources(self, include_deleted: bool = False) -> list[dict[str, Any]]: ...
    def get_source(self, source_id: str, include_deleted: bool = True) -> dict[str, Any] | None: ...
    def get_version(self, version_id: str) -> dict[str, Any] | None: ...
    def versions_for_source(self, source_id: str) -> list[dict[str, Any]]: ...
    def update_source_metadata(self, source_id: str, values: dict[str, Any]) -> dict[str, Any] | None: ...
    def update_rights(self, source_id: str, rights: str) -> dict[str, Any] | None: ...
    def metadata_revisions_for_source(self, source_id: str) -> list[dict[str, Any]]: ...
    def add_relation(self, source_id: str, related_source_id: str, relation_type: str) -> dict[str, Any]: ...
    def relations_for_source(self, source_id: str) -> list[dict[str, Any]]: ...
    def update_processing(self, source_id: str, state: str) -> None: ...
    def set_version_completeness(self, version_id: str, completeness: str) -> None: ...
    def create_representation(self, version_id: str, kind: str, parser_name: str, config_hash: str, text: str, parent_id: str | None = None) -> dict[str, Any]: ...
    def representations_for_version(self, version_id: str) -> list[dict[str, Any]]: ...
    def get_representation(self, representation_id: str) -> dict[str, Any] | None: ...
    def create_search_chunks(self, source_id: str, version_id: str, representation_id: str, chunks: list[tuple[str, str]]) -> list[dict[str, Any]]: ...
    def search_chunks_for_representation(self, representation_id: str) -> list[dict[str, Any]]: ...
    def create_evidence(self, **values: Any) -> dict[str, Any]: ...
    def evidence_for_representation(self, representation_id: str) -> list[dict[str, Any]]: ...
    def get_evidence(self, evidence_id: str) -> dict[str, Any] | None: ...
    def create_citation(self, evidence_id: str) -> dict[str, Any]: ...
    def citations_for_evidence(self, evidence_id: str) -> list[dict[str, Any]]: ...
    def citation_details(self, citation_id: str) -> dict[str, Any] | None: ...
    def create_knowledge(self, kind: str, statement: str, evidence_ids: list[str]) -> dict[str, Any]: ...
    def get_knowledge(self, knowledge_id: str) -> dict[str, Any] | None: ...
    def list_knowledge(self, published_only: bool = False) -> list[dict[str, Any]]: ...
    def publish_knowledge(self, knowledge_id: str) -> dict[str, Any] | None: ...
    def create_job(self, kind: str, source_id: str | None, version_id: str | None, artifact_sha256: str | None, config_hash: str | None, payload: dict[str, Any], priority: int = 0) -> dict[str, Any]: ...
    def list_jobs(self) -> list[dict[str, Any]]: ...
    def get_job(self, job_id: str) -> dict[str, Any] | None: ...
    def claim_next_job(self) -> dict[str, Any] | None: ...
    def update_job(self, job_id: str, *, state: str | None = None, progress: int | None = None, message: str | None = None, done: bool = False) -> None: ...
    def touch_job(self, job_id: str) -> None: ...
    def request_cancel(self, job_id: str) -> dict[str, Any] | None: ...
    def retry_job(self, job_id: str) -> dict[str, Any] | None: ...
    def job_cancel_requested(self, job_id: str) -> bool: ...
    def create_external_card(self, card_type: str, url: str, title: str, author: str | None, notes: str | None, tags: list[str]) -> dict[str, Any]: ...
    def list_external_cards(self) -> list[dict[str, Any]]: ...
    def create_topic(self, name: str, source_ids: list[str]) -> dict[str, Any]: ...
    def list_topics(self) -> list[dict[str, Any]]: ...
    def add_source_to_topic(self, topic_id: str, source_id: str) -> bool: ...
    def soft_delete_source(self, source_id: str) -> dict[str, Any] | None: ...
    def restore_source(self, source_id: str) -> dict[str, Any] | None: ...
    def delete_artifact_if_unreferenced(self, sha256: str) -> bool: ...
    def purge_source(self, source_id: str) -> list[str]: ...
    def rows_for_export(self) -> dict[str, list[dict[str, Any]]]: ...
    def insert_export_rows(self, rows: dict[str, list[dict[str, Any]]]) -> None: ...
    def rows_for_backup(self) -> dict[str, list[dict[str, Any]]]: ...
    def insert_backup_rows(self, rows: dict[str, list[dict[str, Any]]]) -> None: ...
    def prepare_backup_restore(self) -> None: ...
    def has_user_records(self) -> bool: ...
    def create_backup_record(self, archive_name: str, manifest_sha256: str, state: str = "succeeded") -> dict[str, Any]: ...
    def delete_backup_record(self, backup_id: str) -> None: ...
    def update_backup_state(self, backup_id: str, state: str) -> None: ...
    def list_backups(self) -> list[dict[str, Any]]: ...
