[alembic]
script_location = %(here)s/alembic
sqlalchemy.url = postgresql+psycopg://yuanzhiku:yuanzhiku_local_only@postgres:5432/yuanzhiku

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = WARN
handlers =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic
